### ISSUE TITLE
RuntimeError: Cannot install on Python version 3.11.1; only versions >=3.7,<3.11 are supported.

### ISSUE THREAD

**Issue by Pokealec** [robit-man/GLaDOS-TTS#1]
I had an issue when trying to run this file. I was installing everything correctly I think, but this came up:

PS C:\Users\elder\Documents\BYU Idaho\CSE111 Programming with Functions\GLaDOS-TTS> pip3 install -r requirements.txt
Collecting numpy==1.18.0 (from -r requirements.txt (line 1))
  Using cached numpy-1.18.0.zip (5.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting librosa==0.6.3 (from -r requirements.txt (line 2))
  Using cached librosa-0.6.3.tar.gz (1.6 MB)
  Preparing metadata (setup.py) ... done
Collecting gTTS==2.2.2 (from -r requirements.txt (line 3))
  Using cached gTTS-2.2.2-py3-none-any.whl (25 kB)
Collecting playsound==1.2.2 (from -r requirements.txt (line 4))
  Using cached playsound-1.2.2-py2.py3-none-any.whl (6.0 kB)
Requirement already satisfied: pydub==0.25.1 in c:\users\elder\appdata\local\programs\python\python311\lib\site-packages (from -r requirements.txt (line 5)) (0.25.1)
Requirement already satisfied: audioread>=2.0.0 in c:\users\elder\appdata\local\programs\python\python311\lib\site-packages (from librosa==0.6.3->-r requirements.txt (line 2)) (3.0.0)
Requirement already satisfied: scipy>=1.0.0 in c:\users\elder\appdata\local\programs\python\python311\lib\site-packages (from librosa==0.6.3->-r requirements.txt (line 2)) (1.10.1)
Requirement already satisfied: scikit-learn!=0.19.0,>=0.14.0 in c:\users\elder\appdata\local\programs\python\python311\lib\site-packages (from librosa==0.6.3->-r requirements.txt (line 2)) (1.2.2)
Requirement already satisfied: joblib>=0.12 in c:\users\elder\appdata\local\programs\python\python311\lib\site-packages (from librosa==0.6.3->-r requirements.txt (line 2)) (1.2.0)
Requirement already satisfied: decorator>=3.0.0 in c:\users\elder\appdata\local\programs\python\python311\lib\site-packages (from librosa==0.6.3->-r requirements.txt (line 2)) (5.1.1)
Requirement already satisfied: six>=1.3 in c:\users\elder\appdata\local\programs\python\python311\lib\site-packages (from librosa==0.6.3->-r requirements.txt (line 2)) (1.16.0)
Collecting resampy>=0.2.0 (from librosa==0.6.3->-r requirements.txt (line 2))
  Using cached resampy-0.4.2-py3-none-any.whl (3.1 MB)
Requirement already satisfied: numba>=0.38.0 in c:\users\elder\appdata\local\programs\python\python311\lib\site-packages (from librosa==0.6.3->-r requirements.txt (line 2)) (0.57.0)
Requirement already satisfied: click in c:\users\elder\appdata\local\programs\python\python311\lib\site-packages (from gTTS==2.2.2->-r requirements.txt (line 3)) (8.1.3)
Requirement already satisfied: requests in c:\users\elder\appdata\local\programs\python\python311\lib\site-packages (from gTTS==2.2.2->-r requirements.txt (line 3)) (2.30.0)
Requirement already satisfied: llvmlite<0.41,>=0.40.0dev0 in c:\users\elder\appdata\local\programs\python\python311\lib\site-packages (from numba>=0.38.0->librosa==0.6.3->-r requirements.txt (line 2)) (0.40.0)
INFO: pip is looking at multiple versions of numba to determine which version is compatible with other requirements. This could take a while.
Collecting numba>=0.38.0 (from librosa==0.6.3->-r requirements.txt (line 2))
  Using cached numba-0.56.4.tar.gz (2.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\elder\AppData\Local\Temp\pip-install-l5fcelyt\numba_c84b6913bd354a048e8531645a6f75bf\setup.py", line 51, in <module>
          _guard_py_ver()
        File "C:\Users\elder\AppData\Local\Temp\pip-install-l5fcelyt\numba_c84b6913bd354a048e8531645a6f75bf\setup.py", line 48, in _guard_py_ver     
          raise RuntimeError(msg.format(cur_py, min_py, max_py))
      RuntimeError: Cannot install on Python version 3.11.1; only versions >=3.7,<3.11 are supported.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

What do I do? If I understand right, it's saying that something can't install on this newer python version.

**Comment by robit-man** [comment]
Ah yes, this project is quite old, I recommend running in virtualenv with relevant python install sub 3.11
